// Copyright (c) 2026 by Stefan Egli. All rights reserved.

using System;
using System.IO;
using System.Linq;
using System.Text;

using Microsoft.CodeAnalysis.CSharp;

using Xunit;

namespace PNFmt.Tests.Formatter.CSharp
{
    public sealed class CSharpFileHeaderTests
    {
        [Theory]
        [InlineData("class C { }", "// License\n\nclass C { }")]
        [InlineData("\n\nclass C { }\n", "// License\n\nclass C { }\n")]
        [InlineData("// Old\n// Header\n\nclass C { }", "// License\n\nclass C { }")]
        [InlineData("// Old\nclass C { }", "// License\n\nclass C { }")]
        [InlineData("/* Old\n * Header\n */\nclass C { }", "// License\n\nclass C { }")]
        [InlineData("/* Old */ class C { }", "// License\n\nclass C { }")]
        [InlineData("// Old\n\n// Explanation\nclass C { }", "// License\n\n// Explanation\nclass C { }")]
        [InlineData("// Old\n\n \n// Explanation\nclass C { }", "// License\n\n// Explanation\nclass C { }")]
        [InlineData("/// <summary>C</summary>\nclass C { }", "// License\n\n/// <summary>C</summary>\nclass C { }")]
        [InlineData("/** <summary>C</summary> */\nclass C { }", "// License\n\n/** <summary>C</summary> */\nclass C { }")]
        [InlineData("// Old\n/// <summary>C</summary>\nclass C { }", "// License\n\n/// <summary>C</summary>\nclass C { }")]
        public void Adds_or_updates_the_leading_header_and_preserves_later_comments(string input, string expected)
        {
            Assert.Equal(expected, Format(input, "License"));
        }

        [Theory]
        [InlineData("pnfmt_format")]
        [InlineData("pnfmt_csharp_format")]
        public void Disabled_layout_does_not_apply_headers(string setting)
        {
            const string Input = "class C{ }";
            Assert.Equal(Input, Format(Input, "License", options: new[] { (setting, "false") }));
        }

        [Fact]
        public void Empty_file_honors_explicit_final_newline()
        {
            Assert.Equal("// License\n", Format("", "License", options: new[] { ("end_of_line", "lf"), ("insert_final_newline", "true") }));
        }

        [Theory]
        [InlineData("// pnfmt: off\nclass C{ }\n// pnfmt: on\n")]
        [InlineData("// pnfmt: off\nclass C{ }")]
        [InlineData("// pnfmt: off\n// Old\n// pnfmt: on\nclass C { }\n")]
        public void Excluded_headers_and_opening_markers_are_preserved(string input)
        {
            Assert.Equal(input, Format(input, "License"));
        }

        [Theory]
        [InlineData("Sample.g.cs", "class C{ }")]
        [InlineData("Sample.cs", "// <auto-generated/>\nclass C{ }")]
        [InlineData("Sample.cs", "class C {")]
        public void Generated_and_invalid_files_are_skipped_before_header_replacement(string name, string input)
        {
            using (var directory = new TestDirectory())
            {
                directory.Write(".editorconfig", "root = true\n[*.cs]\npnfmt_enabled = true\npnfmt_formatter = csharp\nfile_header_template = License\n");
                var path = directory.Write(name, input);
                Assert.Equal(FileFormatStatus.Skipped, new CSharpFormatter().Format(new FileFormatRequest(path, true, false, NullFormatterLog.Instance)).Status);
                Assert.Equal(input, File.ReadAllText(path));
            }
        }

        [Theory]
        [InlineData("", "// License")]
        [InlineData("\n\n", "// License\n")]
        [InlineData("// Old", "// License")]
        [InlineData("/* Old */\n", "// License\n")]
        public void Handles_empty_and_comment_only_files(string input, string expected)
        {
            Assert.Equal(expected, Format(input, "License"));
        }

        [Fact]
        public void Header_templates_compose_with_sorting_wrapping_and_blank_line_preferences()
        {
            const string Input = "// Old\nusing Z; using A;\nclass C { static public void M(int x, int y) { } }";
            var result = Format(Input, "License", options: new[]
            {
                ("pnfmt_sort_entries", "true"), ("pnfmt_csharp_sort_modifiers", "true"),
                ("pnfmt_csharp_sort_members", "true"), ("csharp_wrap_parameters_style", "chop_always"),
                ("dotnet_style_allow_multiple_blank_lines_experimental", "false"),
                ("csharp_style_allow_blank_lines_between_consecutive_braces_experimental", "false"),
                ("dotnet_style_allow_statement_immediately_after_block_experimental", "false"),
            });
            Assert.StartsWith("// License\n\nusing A;\nusing Z;", result);
            Assert.Contains("public static void M(\n", result);
        }

        [Theory]
        [InlineData("// pnfmt: on\nclass C { }", "// License\n\n// pnfmt: on\nclass C { }")]
        [InlineData("// Old\n// pnfmt: off\nclass C{ }\n// pnfmt: on\n", "// License\n\n// pnfmt: off\nclass C{ }\n// pnfmt: on\n")]
        public void Headers_can_precede_exclusions_without_consuming_markers(string input, string expected)
        {
            Assert.Equal(expected, Format(input, "License"));
        }

        [Theory]
        [InlineData("// License\nclass C { }")]
        [InlineData("//   License  \n\nclass C { }")]
        [InlineData("/* License */\nclass C { }")]
        [InlineData("/*\n * License\n */\n\nclass C { }")]
        public void Matching_line_and_block_headers_keep_their_style(string input)
        {
            Assert.Equal(CSharpFormatterTests.Format(input), Format(input, "License"));
        }

        [Theory]
        [InlineData(null)]
        [InlineData("")]
        [InlineData(" ")]
        [InlineData("unset")]
        [InlineData("UNSET")]
        public void Missing_empty_and_unset_templates_leave_headers_alone(string template)
        {
            const string Input = "// Keep\n\nclass C { }";
            Assert.Equal(Input, Format(Input, template));
        }

        [Theory]
        [InlineData("#nullable enable\nclass C { }", "// License\n\n#nullable enable\nclass C { }")]
        [InlineData("#nullable enable\n// Old\nclass C { }", "#nullable enable\n// License\n\nclass C { }")]
        [InlineData("#if FEATURE\n// Inactive\nclass D{}\n#endif\nclass C { }", "// License\n\n#if FEATURE\n// Inactive\nclass D{}\n#endif\nclass C { }")]
        [InlineData("// Old\n#pragma warning disable\nclass C { }", "// License\n\n#pragma warning disable\nclass C { }")]
        public void Preserves_directives_and_inactive_text(string input, string expected)
        {
            Assert.Equal(expected, Format(input, "License"));
        }

        [Fact]
        public void Public_formatter_resolves_templates_preserves_encoding_and_supports_preview()
        {
            using (var directory = new TestDirectory())
            {
                directory.Write(".editorconfig", "root = true\n[*.cs]\npnfmt_enabled = true\npnfmt_formatter = csharp\n"
                    + "file_header_template = Copyright {fileName}\\nAll rights reserved.\nend_of_line = lf\n");
                var path = directory.GetPath("Sample.cs");
                const string Input = "class C{ }";
                File.WriteAllText(path, Input, new UnicodeEncoding(false, true));
                var original = File.ReadAllBytes(path);
                var formatter = new CSharpFormatter();
                Assert.Equal(FileFormatStatus.Updated, formatter.Format(new FileFormatRequest(path, false, false, NullFormatterLog.Instance)).Status);
                Assert.Equal(original, File.ReadAllBytes(path));
                Assert.Equal(FileFormatStatus.Updated, formatter.Format(new FileFormatRequest(path, true, false, NullFormatterLog.Instance)).Status);
                Assert.Equal("// Copyright Sample.cs\n// All rights reserved.\n\nclass C { }", File.ReadAllText(path));
                Assert.Equal(new byte[] { 0xff, 0xfe }, File.ReadAllBytes(path).Take(2));
                Assert.Equal(FileFormatStatus.Unchanged, formatter.Format(new FileFormatRequest(path, true, false, NullFormatterLog.Instance)).Status);
            }
        }

        [Fact]
        public void Replaces_filename_placeholders_with_the_actual_basename()
        {
            Assert.Equal("// Sample.cs belongs here: Sample.cs\n\nclass C { }",
                Format("class C { }", "{fileName} belongs here: {fileName}", Path.Combine("nested", "Sample.cs")));
        }

        [Fact]
        public void Supports_multiline_templates_blank_comment_lines_and_literal_backslashes()
        {
            Assert.Equal("// Copyright\n//\n// Path C:\\tools; severity:warning\n\nclass C { }",
                Format("class C { }", "Copyright\\n\\nPath C:\\tools; severity:warning  "));
            const string Existing = "/* Copyright\n * Second line\n */\nclass C { }";
            Assert.Equal(CSharpFormatterTests.Format(Existing), Format(Existing, "Copyright\\nSecond line"));
        }

        [Fact]
        public void Templates_do_not_activate_file_processing_and_can_be_unset_in_child_configuration()
        {
            using (var directory = new TestDirectory())
            {
                directory.Write(".editorconfig", "root = true\n[*.cs]\nfile_header_template = License\n");
                var path = directory.Write("Sample.cs", "class C{ }");
                var formatter = new CSharpFormatter();
                Assert.Equal(FileFormatStatus.Skipped, formatter.Format(new FileFormatRequest(path, true, false, NullFormatterLog.Instance)).Status);
                directory.Write("nested/.editorconfig", "[*.cs]\npnfmt_enabled = true\npnfmt_formatter = csharp\nfile_header_template = unset\n");
                path = directory.Write("nested/Other.cs", "class C{ }");
                Assert.Equal(FileFormatStatus.Updated, formatter.Format(new FileFormatRequest(path, true, false, NullFormatterLog.Instance)).Status);
                Assert.Equal("class C { }", File.ReadAllText(path));
            }
        }

        [Theory]
        [InlineData("lf", "\n")]
        [InlineData("crlf", "\r\n")]
        [InlineData("cr", "\r")]
        public void Uses_configured_or_detected_newlines_and_preserves_eof(string style, string newline)
        {
            var options = new[] { ("end_of_line", style) };
            Assert.Equal("// First" + newline + "// Second" + newline + newline + "class C { }",
                Format("class C { }", "First\\nSecond", options: options));
            Assert.Equal("// License" + newline + newline + "class C { }" + newline,
                Format("class C { }" + newline, "License"));
            Assert.Equal("// License" + newline + newline + "class C { }" + newline,
                Format("class C { }", "License", options: new[] { ("end_of_line", style), ("insert_final_newline", "true") }));
        }

        private static string Format(string input, string template, string filePath = "Source.cs", params (string Key, string Value)[] options)
        {
            var settings = options.ToDictionary(option => option.Key, option => option.Value);
            if (template is not null)
            {
                settings["file_header_template"] = template;
            }
            var result = CSharpDocumentFormatter.Format(input, settings, out var diagnostic, filePath);
            Assert.Null(diagnostic);
            Assert.Equal(result, CSharpDocumentFormatter.Format(result, settings, out diagnostic, filePath));
            Assert.Null(diagnostic);
            if (!settings.ContainsKey("pnfmt_sort_entries"))
            {
                Assert.Equal(CSharpSyntaxTree.ParseText(input).GetRoot().DescendantTokens().Select(token => token.Text),
                    CSharpSyntaxTree.ParseText(result).GetRoot().DescendantTokens().Select(token => token.Text));
            }
            return result;
        }
    }
}
