// Copyright (c) 2026 by Stefan Egli. All rights reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using Microsoft.CodeAnalysis.CSharp;

using Xunit;

namespace PNFmt.Tests.Formatter.CSharp
{
    public sealed class CSharpFormatterTests
    {
        public static IEnumerable<object[]> Encodings => new Encoding[]
        {
            new UTF8Encoding(false, true), new UTF8Encoding(true, true),
            new UnicodeEncoding(false, true, true), new UnicodeEncoding(true, true, true),
            new UTF32Encoding(false, true, true), new UTF32Encoding(true, true, true),
        }.Select(encoding => new object[] { encoding });

        [Fact]
        public void Concurrent_files_keep_their_own_settings()
        {
            Parallel.For(1, 9, width =>
            {
                var result = Format("class C\n{\nvoid M() { }\n}\n", ("indent_size", width.ToString()));
                Assert.Contains("\n" + new string(' ', width) + "void M()", result);
            });
        }

        [Theory]
        [InlineData("Source.g.cs", "class C{ }", null, true)]
        [InlineData("Source.g.i.cs", "class C{ }", null, true)]
        [InlineData("Source.GENERATED.cs", "class C{ }", null, true)]
        [InlineData("Source.Designer.cs", "class C{ }", null, true)]
        [InlineData("Source.cs", "// <auto-generated/>\nclass C{ }", null, true)]
        [InlineData("Source.cs", "/* <autogenerated> */\nclass C{ }", null, true)]
        [InlineData("Source.cs", "class C{ }", "true", true)]
        [InlineData("Source.g.cs", "// <auto-generated/>\nclass C{ }", "false", false)]
        [InlineData("Source.cs", "class C{ string s = \"<auto-generated/>\"; }", null, false)]
        [InlineData("Source.cs", "class C{ /* <auto-generated/> */ }", null, false)]
        public void Detects_generated_files_and_honors_explicit_overrides(string name, string text, string setting, bool expected)
        {
            var settings = Settings();
            if (setting is not null)
            {
                settings["generated_code"] = setting;
            }

            Assert.Equal(expected, CSharpGeneratedCode.IsGenerated(name, text, settings));
        }

        [Fact]
        public void File_formatter_is_opt_in_and_supports_preview_and_idempotence()
        {
            using (var directory = new TemporarySource("class C{\nvoid M(){ }\n}"))
            {
                var formatter = new CSharpFormatter();
                var original = File.ReadAllText(directory.FilePath);
                Assert.Equal(FileFormatStatus.Skipped, directory.Run(formatter, true).Status);
                directory.Configure("pnfmt_sort_entries = true\n");
                Assert.Equal(FileFormatStatus.Skipped, directory.Run(formatter, true).Status);
                directory.Configure("pnfmt_csharp_format = true\nindent_size = 2\ninsert_final_newline = true\n");

                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, false).Status);
                Assert.Equal(original, File.ReadAllText(directory.FilePath));
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, true).Status);
                Assert.Contains("\n  void M()", File.ReadAllText(directory.FilePath));
                Assert.Equal(FileFormatStatus.Unchanged, directory.Run(formatter, true).Status);
            }
        }

        [Fact]
        public void File_formatter_member_sorting_honors_editorconfig_and_preview()
        {
            const string Input = "class C { public void Z() { } private void A() { } }";
            using (var directory = new TemporarySource(Input))
            {
                var formatter = new CSharpFormatter();
                directory.Configure("pnfmt_csharp_sort_members = true\n");
                Assert.Equal(FileFormatStatus.Skipped, directory.Run(formatter, true).Status);
                Assert.Equal(Input, File.ReadAllText(directory.FilePath));
                directory.Configure("pnfmt_csharp_format = true\npnfmt_csharp_sort_members = true\n"
                    + "pnfmt_csharp_member_accessibility_order = private,public\n");
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, false).Status);
                Assert.Equal(Input, File.ReadAllText(directory.FilePath));
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, true).Status);
                var result = File.ReadAllText(directory.FilePath);
                Assert.True(result.IndexOf("void A", StringComparison.Ordinal) < result.IndexOf("void Z", StringComparison.Ordinal));
                Assert.Equal(FileFormatStatus.Unchanged, directory.Run(formatter, true).Status);
            }
        }

        [Fact]
        public void File_formatter_region_removal_supports_activation_preview_and_generated_file_detection()
        {
            const string Input = "#region Remove\nclass C { }\n#endregion\n";
            using (var directory = new TemporarySource(Input))
            {
                var formatter = new CSharpFormatter();
                directory.Configure("pnfmt_csharp_remove_regions = true\n");
                Assert.Equal(FileFormatStatus.Skipped, directory.Run(formatter, true).Status);
                Assert.Equal(Input, File.ReadAllText(directory.FilePath));
                directory.Configure("pnfmt_csharp_format = true\npnfmt_csharp_remove_regions = true\n");
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, false).Status);
                Assert.Equal(Input, File.ReadAllText(directory.FilePath));
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, true).Status);
                Assert.Equal("class C { }\n", File.ReadAllText(directory.FilePath));
                Assert.Equal(FileFormatStatus.Unchanged, directory.Run(formatter, true).Status);

                const string Generated = "// <auto-generated/>\n" + Input;
                File.WriteAllText(directory.FilePath, Generated);
                Assert.Equal(FileFormatStatus.Skipped, directory.Run(formatter, true).Status);
                Assert.Equal(Generated, File.ReadAllText(directory.FilePath));
            }
        }

        [Fact]
        public void File_with_syntax_errors_is_not_written()
        {
            using (var directory = new TemporarySource("class C{"))
            {
                directory.Configure("pnfmt_csharp_format = true\n");
                var result = directory.Run(new CSharpFormatter(), true);
                Assert.Equal(FileFormatStatus.Skipped, result.Status);
                Assert.Equal("PNFMT002", Assert.Single(result.Diagnostics).Code);
                Assert.Equal("class C{", File.ReadAllText(directory.FilePath));
            }
        }

        [Fact]
        public void Final_newline_is_optional_and_existing_newlines_are_preserved_by_default()
        {
            Assert.Equal("class C { }", Format("class C { }"));
            Assert.Equal("class C { }\n", Format("class C { }", ("insert_final_newline", "true")));
            Assert.Equal("class C { }\r\n", Format("class C { }\r\n"));
            Assert.Equal("", Format("", ("insert_final_newline", "true")));
        }

        [Fact]
        public void Formats_indentation_spacing_and_braces_without_a_project()
        {
            const string Input = "class C{\nvoid M(){\nif(true){\nM();\n}\n}\n}\n";
            var result = Format(Input, ("indent_size", "2"), ("csharp_new_line_before_open_brace", "all"));

            Assert.Equal("class C\n{\n  void M()\n  {\n    if (true)\n    {\n      M();\n    }\n  }\n}\n", result);
            Assert.Equal(result, Format(result, ("indent_size", "2"), ("csharp_new_line_before_open_brace", "all")));
        }

        [Fact]
        public void Generated_files_are_skipped_before_syntax_validation()
        {
            const string Input = "// <auto-generated/>\nclass C{";
            using (var directory = new TemporarySource(Input))
            {
                directory.Configure("pnfmt_csharp_format = true\n");
                var result = directory.Run(new CSharpFormatter(), true);
                Assert.Equal(FileFormatStatus.Skipped, result.Status);
                Assert.Empty(result.Diagnostics);
                Assert.Equal(Input, File.ReadAllText(directory.FilePath));
                directory.Configure("pnfmt_csharp_format = true\ngenerated_code = false\n");
                Assert.Equal("PNFMT002", Assert.Single(directory.Run(new CSharpFormatter(), true).Diagnostics).Code);
            }
        }

        [Fact]
        public void Honors_tabs_spacing_and_same_line_braces()
        {
            var result = Format("class C\n{\nvoid M()\n{\nif(true)\n{\nM();\n}\n}\n}\n",
                ("indent_style", "tab"), ("indent_size", "4"), ("tab_width", "4"),
                ("csharp_new_line_before_open_brace", "none"),
                ("csharp_space_after_keywords_in_control_flow_statements", "false"));

            Assert.Contains("class C {\n\tvoid M() {\n\t\tif(true) {\n\t\t\tM();", result);
        }

        [Theory]
        [InlineData("class C{", "PNFMT002")]
        [InlineData("class C { void M( }", "PNFMT002")]
        public void Invalid_syntax_is_skipped_with_a_diagnostic(string input, string code)
        {
            var result = CSharpDocumentFormatter.Format(input, Settings(), out var diagnostic);

            Assert.Equal(input, result);
            Assert.Equal(code, diagnostic.Code);
            Assert.Equal(1, diagnostic.LineNumber);
        }

        [Fact]
        public void Invalid_utf8_is_rejected_without_changing_bytes()
        {
            using (var directory = new TemporarySource(""))
            {
                directory.Configure("pnfmt_csharp_format = true\n");
                var bytes = new byte[] { 0x63, 0xC3, 0x28 };
                File.WriteAllBytes(directory.FilePath, bytes);
                Assert.Throws<DecoderFallbackException>(() => directory.Run(new CSharpFormatter(), true));
                Assert.Equal(bytes, File.ReadAllBytes(directory.FilePath));
            }
        }

        [Theory]
        [MemberData(nameof(Encodings))]
        public void Preserves_encoding_bom_and_non_ascii_text(Encoding encoding)
        {
            const string Input = "class C{\nstring s=\"Grüezi 日本語 😀\";\n}\n";
            using (var directory = new TemporarySource(Input))
            {
                directory.Configure("pnfmt_csharp_format = true\n");
                File.WriteAllText(directory.FilePath, Input, encoding);
                var original = File.ReadAllBytes(directory.FilePath);
                var formatter = new CSharpFormatter();
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, false).Status);
                Assert.Equal(original, File.ReadAllBytes(directory.FilePath));
                Assert.Equal(FileFormatStatus.Updated, directory.Run(formatter, true).Status);
                var expected = encoding.GetPreamble().Concat(encoding.GetBytes(Format(Input))).ToArray();
                Assert.Equal(expected, File.ReadAllBytes(directory.FilePath));
                Assert.Equal(FileFormatStatus.Unchanged, directory.Run(formatter, true).Status);
                Assert.Equal(expected, File.ReadAllBytes(directory.FilePath));
            }
        }

        [Fact]
        public void Preserves_inactive_branches_and_directives()
        {
            const string Input = "#if FEATURE\nthis is deliberately invalid C#   \n#else\nclass C{\nvoid M(){ }\n}\n#endif\n";
            var result = Format(Input, ("trim_trailing_whitespace", "true"));

            Assert.Contains("this is deliberately invalid C#   \n", result);
            Assert.Contains("class C\n{", result);
            Assert.Contains("#else\n", result);
            Assert.Equal(result, Format(result, ("trim_trailing_whitespace", "true")));
        }

        [Fact]
        public void Preserves_literals_while_cleaning_code_whitespace()
        {
            const string Input = "class C{\nstring a = @\"first  \r\nsecond  \";  \n"
                + "string b = \"\"\"\n    first  \n    second\n    \"\"\";  \n}\n";
            var result = Format(Input, ("trim_trailing_whitespace", "true"), ("end_of_line", "crlf"));

            Assert.Equal(Literals(Input), Literals(result));
            Assert.Contains(";\r\n", result);
            Assert.DoesNotContain(";  \n", result);
            Assert.Equal(result, Format(result, ("trim_trailing_whitespace", "true"), ("end_of_line", "crlf")));
        }

        internal static string Format(string text, params (string Key, string Value)[] settings)
        {
            var result = CSharpDocumentFormatter.Format(text, Settings(settings), out var diagnostic);
            Assert.Null(diagnostic);
            return result;
        }

        private static string[] Literals(string text)
        {
            return CSharpSyntaxTree.ParseText(text).GetRoot().DescendantTokens()
                .Where(token => token.Kind().ToString().Contains("StringLiteralToken"))
                .Select(token => token.Text).ToArray();
        }

        private static Dictionary<string, string> Settings(params (string Key, string Value)[] settings)
        {
            return settings.ToDictionary(item => item.Key, item => item.Value);
        }

        private sealed class TemporarySource : IDisposable
        {
            private readonly TestDirectory directory = new TestDirectory();

            public TemporarySource(string text)
            {
                File.WriteAllText(this.FilePath, text);
                this.Configure(string.Empty);
            }

            public string FilePath => this.directory.GetPath("Source.cs");

            public void Configure(string settings)
            {
                this.directory.Write(".editorconfig", "root = true\n\n[*.cs]\n" + settings);
            }

            public void Dispose() => this.directory.Dispose();

            public FileFormatResult Run(IFileFormatter formatter, bool write)
            {
                return formatter.Format(new FileFormatRequest(this.FilePath, write, false, NullFormatterLog.Instance));
            }
        }
    }
}
