// Copyright (c) 2026 by Stefan Egli. All rights reserved.

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace PNFmt
{
    internal static class CSharpGeneratedCode
    {
        public static bool IsGenerated(string path, string text, IReadOnlyDictionary<string, string> settings)
        {
            if (settings.TryGetValue("generated_code", out var value) && bool.TryParse(value, out var generated))
            {
                return generated;
            }

            var name = Path.GetFileName(path);
            if (new[] { ".g.cs", ".g.i.cs", ".generated.cs", ".designer.cs" }
                .Any(suffix => name.EndsWith(suffix, StringComparison.OrdinalIgnoreCase)))
            {
                return true;
            }

            // Only leading comments count; marker-like strings or comments in a method
            // must not make an ordinary file disappear from formatting.
            return CSharpSyntaxTree.ParseText(text).GetRoot().GetLeadingTrivia()
                .Where(trivia => trivia.IsKind(SyntaxKind.SingleLineCommentTrivia)
                    || trivia.IsKind(SyntaxKind.MultiLineCommentTrivia))
                .Any(trivia => trivia.ToString().IndexOf("<auto-generated", StringComparison.OrdinalIgnoreCase) >= 0
                    || trivia.ToString().IndexOf("<autogenerated", StringComparison.OrdinalIgnoreCase) >= 0);
        }
    }
}
