<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\PNFmt.Cli\PNFmt.Cli.csproj" />
        <ProjectReference Include="..\PNFmt.Core\PNFmt.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LibGit2Sharp" Version="0.32.0" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
        <PackageReference Include="NFluent" Version="3.1.0" />
        <PackageReference Include="xunit" Version="2.9.3" />
        <PackageReference Include="xunit.analyzers" Version="1.27.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Remove="Formatter\CsProj\_files\**\*" />
        <EmbeddedResource Remove="Formatter\Ini\_files\**\*" />
        <EmbeddedResource Remove="Formatter\Resx\_editor\**\*" />
        <EmbeddedResource Remove="Formatter\Resx\_files\**\*" />
        <EmbeddedResource Remove="Formatter\Slnx\_files\**\*" />
        <None Remove="Formatter\CsProj\_files\**\*" />
        <None Remove="Formatter\Ini\_files\**\*" />
        <None Remove="Formatter\Resx\_editor\**\*" />
        <None Remove="Formatter\Resx\_files\**\*" />
        <None Remove="Formatter\Slnx\_files\**\*" />
        <Content Include="Formatter\CsProj\_files\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Formatter\Ini\_files\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Formatter\Resx\_editor\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Formatter\Resx\_files\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
        <Content Include="Formatter\Slnx\_files\**\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>
</Project>