[settings]
zulu=last
csharp_style_var=true
indent_style=space
csharp_indent_braces=false
dotnet_style_qualification=false
DOTNET_style_qualification=true
# Prefix groups do not cross this comment.
csharp_style_elsewhere=false
alpha=first
