<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>pnfmt</AssemblyName>
        <Authors>Stefan Egli</Authors>
        <Description>Format .NET project, solution, resource, and configuration files.</Description>
        <OutputType>Exe</OutputType>
        <PackageId>PetchNaka.PNFmt.Cli</PackageId>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageTags>dotnet-tool;editorconfig;formatter;csproj;resx;slnx;ini</PackageTags>
        <PackAsTool>true</PackAsTool>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/stefanegli/PNFmt</RepositoryUrl>
        <RootNamespace>PNFmt.Cli</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
        <ToolCommandName>pnfmt</ToolCommandName>
        <Version>0.1.0-alpha.2</Version>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PNFmt.Tests" />
    </ItemGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\">
            <Link>README.md</Link>
        </None>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PNFmt.Core\PNFmt.Core.csproj" />
    </ItemGroup>
</Project>
