<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ImportGroup Condition="'$(Configuration)' == 'Debug'">
    <Import Project="debug.props" Condition="Exists('debug.props')" />
  </ImportGroup>
  <ItemGroup>
    <None Include="readme.md" />
  </ItemGroup>
</Project>
