<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Zeta\Zeta.csproj" />
        <ProjectReference Include="..\Alpha\Alpha.csproj" />
        <ProjectReference Include="..\Beta\Beta.csproj" />
    </ItemGroup>
    <ItemGroup>
        <Reference Include="System.Xml" />
        <Reference Include="System" />
        <Reference Include="System.Core" />
    </ItemGroup>
    <ItemGroup>
        <None Include="b.txt" />
        <None Include="a.txt" />
        <None Include="c.txt" />
    </ItemGroup>
</Project>
