<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>
    <CustomSettings Enabled="true">
        <Flag>on</Flag>
    </CustomSettings>
    <ItemGroup>
        <None Include="readme.txt" />
    </ItemGroup>
</Project>
