<Project>
    <PropertyGroup>
        <AssemblyName>Sample</AssemblyName>
        <Configuration Condition="'$(Configuration)' == ''">Debug</Configuration>
        <WarningLevel>4</WarningLevel>
    </PropertyGroup>

    <PropertyGroup>
        <ObservedBefore>$(Zebra)</ObservedBefore>
        <Zebra>first</Zebra>
        <ObservedBetween>$(Zebra)</ObservedBetween>
        <Zebra>$(Zebra);second</Zebra>
        <ObservedAfter>$(Zebra)</ObservedAfter>
    </PropertyGroup>

    <ItemDefinitionGroup>
        <Compile>
            <Zebra>default</Zebra>
            <Alpha>%(Zebra)</Alpha>
        </Compile>
    </ItemDefinitionGroup>
</Project>
