[settings]
csharp_indent_braces = false
csharp_style_var = true

dotnet_style_qualification = false
DOTNET_style_qualification = true

indent_style = space
zulu = last
# Prefix groups do not cross this comment.
alpha = first
csharp_style_elsewhere = false
