<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <RootNamespace>PNFmt</RootNamespace>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PNFmt.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="editorconfig" Version="0.15.0" />
    </ItemGroup>
</Project>