<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <FormatterSourceRoot Condition="'$(FormatterSourceRoot)' == ''">$(MSBuildThisFileDirectory)..</FormatterSourceRoot>
        <IsPackable>false</IsPackable>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="$(FormatterSourceRoot)/PNFmt.Cli/PNFmt.Cli.csproj" />
    </ItemGroup>
</Project>
